name: GitHub Contribution Snake

on:
  workflow_dispatch:

permissions:
  contents: write  # important! allows workflow to push

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # must be false to use GITHUB_TOKEN

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kimbi12
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Configure Git
        run: |
          git config user.name "Kimbi Denis"
          git config user.email "kimbidenis67@gmail.com"

      - name: Commit & Push SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add dist/github-contribution-grid-snake.svg
          git diff --cached --quiet || git commit -m "Update snake"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/kimbi12/kimbi12.git HEAD:main
