name: GitHub Contribution Snake

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kimbi12
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Configure Git
        run: |
          git config user.email "kimbidenis67@gmail.com"
          git config user.name "Kimbi Denis"

      - name: Commit & Push SVG
        run: |
          git add dist/github-contribution-grid-snake.svg
          git diff --cached --quiet || git commit -m "Update snake"
          git push
