name: GitHub Contribution Snake

on:
  workflow_dispatch:  # allows you to run manually

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: kimbi12
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Commit SVG
        run: |
          git config --local user.email "kimbidenis67@gmail.com"
          git config --local user.name "Kimbi Denis"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake"
          git push
